"""Shared pytest fixtures for preseed-* script tests.

The scripts under test all derive their workspace location from
``Path.home() / "fundraising"``, so the central trick used here is to
monkey-patch ``Path.home()`` to return a per-test ``tmp_path``. This
gives every test a clean, isolated workspace while still exercising the
real production code paths.
"""

from __future__ import annotations

import csv
import importlib
import os
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest

# Make the script packages importable as plain modules.
SKILLS_ROOT = Path(__file__).resolve().parent.parent
PRESEED_CAMPAIGN_SCRIPTS = SKILLS_ROOT / "preseed-campaign" / "scripts"
PRESEED_VOICE_SCRIPTS = SKILLS_ROOT / "preseed-voice" / "scripts"

for p in (PRESEED_CAMPAIGN_SCRIPTS, PRESEED_VOICE_SCRIPTS):
    sp = str(p)
    if sp not in sys.path:
        sys.path.insert(0, sp)


# ---------------------------------------------------------------------------
# Workspace fixture
# ---------------------------------------------------------------------------

CAMPAIGN_YAML_SEED = """\
version: 1
company: Agentis
stage: pre-seed
target_raise_usd: 1000000
instrument: SAFE
target_first_close_amount_usd: 500000
target_first_close_date: null
current_wave: 0
wave_size_target: 12
lead_candidate_pct: 0.60
wave_started_date: null
campaign_status: setup_complete
story_gate: pending
voice_gate: pending
simple_mode: false
snapshot_on_change: false
last_review_date: null
next_review_date: null
momentum_score: null
momentum_score_prev: null
setup_date: 2026-05-01
"""

VOCABULARY_YAML_SEED = """\
roles:
  - operator_angel
  - micro_vc
statuses:
  - identified
  - intro_call_booked
  - partner_meeting_booked
  - soft_commit
  - replied_positive
  - intro_call_done
confidence:
  - high
  - medium
  - low
"""

SCHEMAS_YAML_SEED = """\
campaign:
  required:
    - version
    - company
    - stage
investors:
  required:
    - investor_id
    - first_name
"""

ANTI_VOICE_TXT_SEED = """\
# anti-voice phrases — banned in all generated outreach.
## defaults
I hope this email finds you well
Just following up
Circling back
leveraging
synergy
world-class
## samples
"""

ROUND_BRIEF_YAML_SEED = """\
# round brief — generated by /preseed-story
one_liner: |
  Agentis stops margin leaks for mid-market Shopify brands in real time.
problem: |
  Mid-market Shopify brands lose 1-3 points of gross margin every month
  to pricing errors, promo overlap, and high-return SKUs.
why_now: |
  Shopify Functions and the new Order API let us read the entire margin
  graph live for the first time.
solution: |
  Real-time profit floor enforcement that rewrites pricing, blocks
  losing promos, and routes returns before they ship.
traction:
  - 2 paid pilots at $4M-$8M GMV
  - $40k MRR
  - 1.8 points of margin recovered in week one
ask:
  raise_usd: 1000000
  instrument: SAFE
  first_close_usd: 500000
team:
  - Herzel Mishel — solo founder, ex-CTO ecom
  - Udi — engineering lead
  - Igor — data
ideal_investor:
  - operator angels with Shopify Plus exits
  - micro VCs writing $50-150k checks
exclusions:
  - retail-only funds without ecom thesis
  - pre-revenue B2C generalists
risks:
  - integration complexity per Shopify version
  - merchant churn on profit floor pushback
"""

VOICE_FINGERPRINT_YAML_SEED = """\
sample_count: 6
avg_sentence_length_words: 14.0
contraction_rate: 0.4
paragraph_avg_sentences: 2.0
em_dash_rate: 0.2
register: casual_direct
technical_density: 0.02
voice_score_threshold: 0.7
confidence: high
opener_patterns:
  - "Quick one —"
  - "Update:"
closer_patterns:
  - "— Herzel"
signature_phrases:
  - margin leaks in real time
banned_default:
  - I hope this email finds you well
  - Just following up
  - leveraging
banned_personal:
  - synergy
preferred_alternatives:
  "I wanted to reach out": "Quick one — "
  "leveraging": "using"
"""


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


@pytest.fixture
def tmp_workspace(tmp_path, monkeypatch):
    """Create a complete ~/fundraising/ workspace under tmp_path.

    Patches ``Path.home()`` so scripts under test write into this fixture
    rather than the real user home.
    """
    monkeypatch.setattr(Path, "home", classmethod(lambda cls: tmp_path))
    monkeypatch.setenv("HOME", str(tmp_path))

    # Stage the preseed-voice anti-voice seed under the patched home so
    # build_campaign.py can find it from Path.home()/.claude/skills/...
    voice_anti = (
        tmp_path / ".claude" / "skills" / "preseed-voice"
        / "references" / "anti-voice-defaults.md"
    )
    voice_anti.parent.mkdir(parents=True, exist_ok=True)
    voice_anti.write_text(
        "# Anti-Voice Defaults\n"
        "## Phrases\n"
        "- I hope this email finds you well\n"
        "- Just following up\n"
        "- Circling back\n"
        "- leveraging\n"
        "- synergy\n"
        "- world-class\n",
        encoding="utf-8",
    )

    root = tmp_path / "fundraising"
    for sub in (
        "",
        ".sys",
        ".sys/logs",
        "voice",
        "voice/samples",
        "story",
        "investors",
        "outreach",
        "prep",
        "pipeline",
    ):
        (root / sub).mkdir(parents=True, exist_ok=True)

    _write(root / "campaign.yaml", CAMPAIGN_YAML_SEED)
    _write(root / ".sys" / "vocabulary.yaml", VOCABULARY_YAML_SEED)
    _write(root / ".sys" / "schemas.yaml", SCHEMAS_YAML_SEED)
    _write(root / ".sys" / "scripts.yaml", "# scripts.yaml seed\n")
    _write(root / ".sys" / "anti-voice.txt", ANTI_VOICE_TXT_SEED)
    _write(root / "story" / "round-brief.yaml", ROUND_BRIEF_YAML_SEED)
    _write(root / "voice" / "voice-fingerprint.yaml",
           VOICE_FINGERPRINT_YAML_SEED)

    return root


@pytest.fixture
def empty_home(tmp_path, monkeypatch):
    """tmp_path that's been monkey-patched as Path.home() but no workspace.

    Also stages the preseed-voice anti-voice-defaults.md under the patched
    home so build_campaign.py's seed step can find it (it reads from
    ``Path.home() / ".claude" / "skills" / "preseed-voice" / "references" /
    "anti-voice-defaults.md"``).
    """
    monkeypatch.setattr(Path, "home", classmethod(lambda cls: tmp_path))
    monkeypatch.setenv("HOME", str(tmp_path))

    voice_anti = (
        tmp_path / ".claude" / "skills" / "preseed-voice"
        / "references" / "anti-voice-defaults.md"
    )
    voice_anti.parent.mkdir(parents=True, exist_ok=True)
    # Mirror enough of the real preseed-voice seed to drive the parser.
    voice_anti.write_text(
        "# Anti-Voice Defaults\n"
        "## Phrases\n"
        "- I hope this email finds you well\n"
        "- Just following up\n"
        "- Circling back\n"
        "- leveraging\n"
        "- synergy\n"
        "- world-class\n",
        encoding="utf-8",
    )
    return tmp_path


# ---------------------------------------------------------------------------
# Seed factories — pytest fixtures that return helper callables
# ---------------------------------------------------------------------------

@pytest.fixture
def seed_round_brief():
    """Factory: write a (possibly-modified) round-brief.yaml to a workspace."""
    def _seed(root: Path, content: str | None = None,
              overrides: dict | None = None) -> Path:
        if content is None:
            content = ROUND_BRIEF_YAML_SEED
        if overrides:
            for key, value in overrides.items():
                # very simple override: replace `key: |\n  ...` block or
                # `key: scalar` line with the new value.
                content = _replace_yaml_top_level(content, key, value)
        path = root / "story" / "round-brief.yaml"
        _write(path, content)
        return path
    return _seed


def _replace_yaml_top_level(text: str, key: str, value) -> str:
    """Helper for tests: replace a top-level YAML key. Best-effort.

    Removes any nested/indented child lines belonging to the previous value
    so a list seed can be replaced with a string (or vice versa) cleanly.
    """
    import re

    if value is None:
        replacement = f"{key}: null\n"
    elif isinstance(value, list):
        body = "\n".join(f"  - {item}" for item in value)
        replacement = f"{key}:\n{body}\n"
    elif isinstance(value, str) and "\n" in value:
        body = "\n".join(f"  {line}" for line in value.splitlines())
        replacement = f"{key}: |\n{body}\n"
    elif isinstance(value, str) and value == "":
        replacement = f"{key}: ''\n"
    elif isinstance(value, str):
        replacement = f"{key}: {value}\n"
    else:
        replacement = f"{key}: {value}\n"

    # Match the key line + all subsequent lines that start with whitespace
    # (the indented children of the original mapping/list/block-scalar).
    full_re = re.compile(
        rf"^{re.escape(key)}:[^\n]*\n(?:[ \t]+[^\n]*\n)*",
        re.MULTILINE,
    )
    if full_re.search(text):
        return full_re.sub(replacement, text, count=1)
    return text + ("\n" if not text.endswith("\n") else "") + replacement


@pytest.fixture
def seed_vocabulary_yaml():
    def _seed(root: Path, content: str | None = None) -> Path:
        path = root / ".sys" / "vocabulary.yaml"
        _write(path, content if content is not None else VOCABULARY_YAML_SEED)
        return path
    return _seed


@pytest.fixture
def seed_schemas_yaml():
    def _seed(root: Path, content: str | None = None) -> Path:
        path = root / ".sys" / "schemas.yaml"
        _write(path, content if content is not None else SCHEMAS_YAML_SEED)
        return path
    return _seed


@pytest.fixture
def seed_anti_voice():
    def _seed(root: Path, content: str | None = None) -> Path:
        path = root / ".sys" / "anti-voice.txt"
        _write(path, content if content is not None else ANTI_VOICE_TXT_SEED)
        return path
    return _seed


@pytest.fixture
def sample_voice_fingerprint():
    def _seed(root: Path, content: str | None = None) -> Path:
        path = root / "voice" / "voice-fingerprint.yaml"
        _write(
            path,
            content if content is not None else VOICE_FINGERPRINT_YAML_SEED,
        )
        return path
    return _seed


@pytest.fixture
def sample_investors_csv():
    """Factory: produce an investor row dict + write investors.csv."""
    def _seed(root: Path, rows: list[dict] | None = None) -> Path:
        path = root / "investors" / "investors.csv"
        if rows is None:
            rows = [{
                "investor_id": "jane-doe-acme-2026",
                "first_name": "Jane",
                "last_name": "Doe",
                "investor_name": "Jane Doe",
                "firm_or_handle": "Acme Capital",
                "role": "operator_angel",
                "lead_candidate": "yes",
                "linkedin_profile_url": "https://linkedin.com/in/jane",
                "public_contact_path": "linkedin",
                "check_size_range": "50000-150000",
                "stage_fit": "pre-seed",
                "domain_fit": "ecommerce",
                "score_100": "82",
            }]
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            for row in rows:
                writer.writerow(row)
        return path
    return _seed


@pytest.fixture
def sample_pipeline_state():
    """Factory: write pipeline.csv + touches.csv + commitments.csv."""
    def _seed(
        root: Path,
        touches: list[dict] | None = None,
        commitments: list[dict] | None = None,
        pipeline: list[dict] | None = None,
    ) -> dict:
        pipeline_dir = root / "pipeline"
        pipeline_dir.mkdir(parents=True, exist_ok=True)

        touches_path = pipeline_dir / "touches.csv"
        if touches is None:
            touches = []
        with touches_path.open("w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(
                f,
                fieldnames=[
                    "investor_id",
                    "touch_date",
                    "channel",
                    "status_before",
                    "status_after",
                    "notes",
                ],
            )
            writer.writeheader()
            for t in touches:
                writer.writerow({**{
                    "investor_id": "",
                    "touch_date": "",
                    "channel": "",
                    "status_before": "",
                    "status_after": "",
                    "notes": "",
                }, **t})

        commitments_path = pipeline_dir / "commitments.csv"
        if commitments is None:
            commitments = []
        with commitments_path.open("w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(
                f,
                fieldnames=[
                    "investor_id",
                    "soft_commit_date",
                    "soft_commit_amount",
                    "signed_safe_date",
                    "signed_safe_amount",
                    "cash_date",
                    "cash_amount",
                    "soft_circle_permission",
                ],
            )
            writer.writeheader()
            for c in commitments:
                writer.writerow({**{
                    "investor_id": "",
                    "soft_commit_date": "",
                    "soft_commit_amount": "",
                    "signed_safe_date": "",
                    "signed_safe_amount": "",
                    "cash_date": "",
                    "cash_amount": "",
                    "soft_circle_permission": "",
                }, **c})

        pipeline_path = pipeline_dir / "pipeline.csv"
        if pipeline is None:
            pipeline = []
        with pipeline_path.open("w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(
                f,
                fieldnames=["investor_id", "status", "last_touch_date"],
            )
            writer.writeheader()
            for p in pipeline:
                writer.writerow({**{
                    "investor_id": "",
                    "status": "",
                    "last_touch_date": "",
                }, **p})

        return {
            "touches": touches_path,
            "commitments": commitments_path,
            "pipeline": pipeline_path,
        }
    return _seed


# ---------------------------------------------------------------------------
# Subprocess runner
# ---------------------------------------------------------------------------

@pytest.fixture
def run_script():
    """Factory: run a script via subprocess with HOME pointed at tmp_path.

    Returns (returncode, stdout, stderr).
    """
    def _run(script_path: Path, args: list[str] | None = None,
             *, home: Path | None = None,
             stdin_text: str | None = None) -> tuple[int, str, str]:
        env = os.environ.copy()
        if home is not None:
            env["HOME"] = str(home)
        cmd = [sys.executable, str(script_path)]
        if args:
            cmd.extend(args)
        proc = subprocess.run(
            cmd,
            input=stdin_text,
            capture_output=True,
            text=True,
            env=env,
            check=False,
        )
        return proc.returncode, proc.stdout, proc.stderr
    return _run


# ---------------------------------------------------------------------------
# Module reload helpers — needed because Python caches modules between
# tests and Path.home() patches must be in effect at module top level.
# ---------------------------------------------------------------------------

@pytest.fixture
def reload_module():
    """Reload a module fresh under the current monkeypatch state."""
    def _reload(name: str):
        if name in sys.modules:
            del sys.modules[name]
        return importlib.import_module(name)
    return _reload
