#!/usr/bin/env python3
"""
ghost_check.py — preseed-pipeline

Reads pipeline.csv and touches.csv. Finds investors where:
  - status in {intro_call_done, partner_meeting_done, data_room_accessed,
              diligence}
  - last_meeting_date is set
  - no row in touches.csv for this investor in the last 14 days from
    max(last_meeting_date, latest touch_date for this investor)

Action for each newly-detected ghost:
  - Sets status = 'ghosted', ghost_flag_date = today (in pipeline.csv)
  - Writes ~/fundraising/outreach/[investor-slug]-takeaway.md with a ≤80-word
    voice-matched draft

Output: JSON list of newly-ghosted investors. Exit 1 on error.
Stdlib only.
"""
from __future__ import annotations

import csv
import json
import re
import sys
from datetime import date, datetime
from pathlib import Path

FUNDRAISING = Path.home() / "fundraising"
PIPELINE_CSV = FUNDRAISING / "pipeline" / "pipeline.csv"
TOUCHES_CSV = FUNDRAISING / "pipeline" / "touches.csv"
OUTREACH_DIR = FUNDRAISING / "outreach"
VOICE_YAML = FUNDRAISING / "voice" / "voice-fingerprint.yaml"

POST_MEETING_STATUSES = {
    "intro_call_done",
    "partner_meeting_done",
    "data_room_accessed",
    "diligence",
}
GHOST_THRESHOLD_DAYS = 14


def emit_error(message: str, field: str, fix: str) -> int:
    print(json.dumps({"error": message, "field": field, "fix": fix}))
    return 1


def parse_iso(value: str) -> date | None:
    value = (value or "").strip()
    if not value:
        return None
    try:
        return datetime.fromisoformat(value).date()
    except ValueError:
        return None


def slugify(value: str) -> str:
    value = (value or "").strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-") or "investor"


def load_voice_register() -> str:
    if not VOICE_YAML.exists():
        return ""
    try:
        for raw in VOICE_YAML.read_text(encoding="utf-8").splitlines():
            stripped = raw.strip()
            if stripped.startswith("register:"):
                return stripped.split(":", 1)[1].strip()
    except OSError:
        return ""
    return ""


def write_takeaway_draft(
    investor_id: str,
    investor_name: str,
    last_meeting_date: str,
    today: str,
    register: str,
) -> Path:
    slug = slugify(investor_name)
    target = OUTREACH_DIR / f"{slug}-takeaway.md"
    OUTREACH_DIR.mkdir(parents=True, exist_ok=True)

    voice_note = (
        f"<!-- voice-fingerprint register={register} -->"
        if register
        else "<!-- voice-fingerprint NOT loaded — run /preseed-voice -->"
    )

    template = f"""# Takeaway Email — {investor_name}

{voice_note}

Generated by ghost_check.py on {today}. ≤80 words. Direct. Forces yes/no.
Never desperate. Never apologetic.

## Context

- Investor: {investor_name} (id: {investor_id})
- Last meeting: {last_meeting_date}
- Status flagged ghosted on: {today}

## Draft

Subject: Pulling the allocation

Hi <FIRST NAME>,

Haven't heard back since {last_meeting_date}. Pulling the allocation back to
the open round.

If I'm reading this wrong, let me know in the next 48 hours and I'll hold.

— Herzel

## Rules

- ≤80 words total (excluding subject and signature). Counted by
  count_message_chars.py before export.
- No "just checking in", no "hope you're well" — both are in
  ~/fundraising/.sys/anti-voice.txt.
- No softening language. The takeaway only works if it forces a yes/no.
- After sending, mark takeaway_sent_date in pipeline.csv. If no reply within
  48 hours, move to pass with pass_reason=ghosted and run reapproach_notes.py.
"""
    target.write_text(template, encoding="utf-8")
    return target


def main() -> int:
    if not PIPELINE_CSV.exists():
        return emit_error(
            "pipeline.csv not found",
            field=str(PIPELINE_CSV),
            fix="Run /preseed-campaign setup.",
        )

    today = date.today()
    today_iso = today.isoformat()
    register = load_voice_register()

    # --- Read touches; build per-investor latest-touch map.
    latest_touch: dict[str, date] = {}
    if TOUCHES_CSV.exists():
        try:
            with TOUCHES_CSV.open("r", encoding="utf-8", newline="") as handle:
                for row in csv.DictReader(handle):
                    iid = (row.get("investor_id") or "").strip()
                    td = parse_iso(row.get("touch_date") or "")
                    if not iid or not td:
                        continue
                    if iid not in latest_touch or td > latest_touch[iid]:
                        latest_touch[iid] = td
        except (OSError, csv.Error) as exc:
            return emit_error(
                f"Failed to read touches.csv: {exc}",
                field=str(TOUCHES_CSV),
                fix="Verify the file is valid CSV with a header row.",
            )

    # --- Read pipeline.csv, scan for ghosts.
    try:
        with PIPELINE_CSV.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            fieldnames = list(reader.fieldnames or [])
            rows = list(reader)
    except (OSError, csv.Error) as exc:
        return emit_error(
            f"Failed to read pipeline.csv: {exc}",
            field=str(PIPELINE_CSV),
            fix="Verify the file is valid CSV with a header row.",
        )

    for col in ("ghost_flag_date", "status"):
        if col not in fieldnames:
            fieldnames.append(col)

    newly_ghosted: list[dict[str, str]] = []
    for row in rows:
        status = (row.get("status") or "").strip()
        if status not in POST_MEETING_STATUSES:
            continue

        last_meeting = parse_iso(row.get("last_meeting_date") or "")
        if not last_meeting:
            continue

        iid = (row.get("investor_id") or "").strip()
        last_touch = latest_touch.get(iid)
        anchor = last_meeting
        if last_touch and last_touch > last_meeting:
            anchor = last_touch

        days_silent = (today - anchor).days
        if days_silent <= GHOST_THRESHOLD_DAYS:
            continue

        # Avoid re-flagging if already ghosted
        if (row.get("ghost_flag_date") or "").strip():
            continue

        # Flag and draft.
        row["status"] = "ghosted"
        row["ghost_flag_date"] = today_iso
        investor_name = (row.get("investor_name") or "").strip() or iid
        try:
            draft_path = write_takeaway_draft(
                iid, investor_name, last_meeting.isoformat(), today_iso, register
            )
        except OSError as exc:
            return emit_error(
                f"Failed to write takeaway draft for {iid}: {exc}",
                field=str(OUTREACH_DIR),
                fix="Verify file permissions on ~/fundraising/outreach/.",
            )

        newly_ghosted.append(
            {
                "investor_id": iid,
                "investor_name": investor_name,
                "last_meeting_date": last_meeting.isoformat(),
                "days_silent": str(days_silent),
                "draft_path": str(draft_path),
            }
        )

    # --- Write pipeline.csv back if we changed anything.
    if newly_ghosted:
        try:
            with PIPELINE_CSV.open("w", encoding="utf-8", newline="") as handle:
                writer = csv.DictWriter(handle, fieldnames=fieldnames)
                writer.writeheader()
                for row in rows:
                    writer.writerow({key: row.get(key, "") for key in fieldnames})
        except OSError as exc:
            return emit_error(
                f"Failed to write pipeline.csv: {exc}",
                field=str(PIPELINE_CSV),
                fix="Verify file permissions on ~/fundraising/pipeline/pipeline.csv.",
            )

    print(
        json.dumps(
            {
                "ok": True,
                "checked_at": today_iso,
                "newly_ghosted": newly_ghosted,
                "newly_ghosted_count": len(newly_ghosted),
            }
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
