#!/usr/bin/env python3
"""
reapproach_notes.py — preseed-pipeline

Triggered after status=pass. Reads pass_reason and reapproach_trigger from
pipeline.csv for the given investor. Loads voice-fingerprint.yaml if present
(the loaded fingerprint informs prose tone — captured in the placeholder
template comments).

Writes ~/fundraising/outreach/[investor-slug]-reapproach.md with placeholders
for the milestone-completion event. The user (or /preseed-outreach) fills in
the final draft once the milestone fires.

Args:
  --investor-id   Required.

Output: JSON on stdout. Exit 1 on error.
Stdlib only.
"""
from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from datetime import date
from pathlib import Path

FUNDRAISING = Path.home() / "fundraising"
PIPELINE_CSV = FUNDRAISING / "pipeline" / "pipeline.csv"
OUTREACH_DIR = FUNDRAISING / "outreach"
VOICE_YAML = FUNDRAISING / "voice" / "voice-fingerprint.yaml"


def emit_error(message: str, field: str, fix: str) -> int:
    print(json.dumps({"error": message, "field": field, "fix": fix}))
    return 1


def slugify(value: str) -> str:
    value = (value or "").strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-") or "investor"


def load_voice_summary() -> dict[str, str]:
    """Pull a few helpful surface-level fields from voice-fingerprint.yaml."""
    summary: dict[str, str] = {}
    if not VOICE_YAML.exists():
        return summary
    try:
        for raw in VOICE_YAML.read_text(encoding="utf-8").splitlines():
            stripped = raw.strip()
            for key in ("register", "voice_score_threshold", "avg_sentence_length_words"):
                if stripped.startswith(f"{key}:"):
                    summary[key] = stripped.split(":", 1)[1].strip()
                    break
    except OSError:
        return {}
    return summary


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--investor-id", required=True)
    args = parser.parse_args()

    if not PIPELINE_CSV.exists():
        return emit_error(
            "pipeline.csv not found",
            field=str(PIPELINE_CSV),
            fix="Run /preseed-campaign setup.",
        )

    target: dict[str, str] | None = None
    try:
        with PIPELINE_CSV.open("r", encoding="utf-8", newline="") as handle:
            for row in csv.DictReader(handle):
                if (row.get("investor_id") or "").strip() == args.investor_id:
                    target = row
                    break
    except (OSError, csv.Error) as exc:
        return emit_error(
            f"Failed to read pipeline.csv: {exc}",
            field=str(PIPELINE_CSV),
            fix="Verify the file is valid CSV.",
        )

    if target is None:
        return emit_error(
            f"investor_id '{args.investor_id}' not found in pipeline.csv",
            field="investor_id",
            fix="Run /preseed-pipeline update for the investor first, or check spelling.",
        )

    pass_reason = (target.get("pass_reason") or "").strip()
    reapproach_trigger = (target.get("reapproach_trigger") or "").strip()
    investor_name = (target.get("investor_name") or "").strip() or args.investor_id

    if not pass_reason or not reapproach_trigger:
        return emit_error(
            "pass_reason and reapproach_trigger must be populated before "
            "drafting the re-approach note.",
            field="pipeline.csv (pass_reason / reapproach_trigger)",
            fix=(
                f"Run update_pipeline.py --investor-id {args.investor_id} "
                f"--new-status pass --pass-reason \"...\" "
                f"--reapproach-trigger \"...\" to populate the fields."
            ),
        )

    voice = load_voice_summary()
    voice_note = ""
    if voice:
        voice_note = (
            f"<!-- voice-fingerprint loaded: register={voice.get('register', 'unknown')}, "
            f"avg_sentence_length_words={voice.get('avg_sentence_length_words', 'unknown')}, "
            f"voice_score_threshold={voice.get('voice_score_threshold', 'unknown')} -->"
        )
    else:
        voice_note = (
            "<!-- voice-fingerprint NOT loaded — run /preseed-voice for voice-matched output. -->"
        )

    slug = slugify(investor_name)
    target_path = OUTREACH_DIR / f"{slug}-reapproach.md"
    OUTREACH_DIR.mkdir(parents=True, exist_ok=True)

    today = date.today().isoformat()
    template = f"""# Re-approach Note — {investor_name}

{voice_note}

Generated by reapproach_notes.py on {today}. This is a draft template.
Send only after the reapproach_trigger milestone has actually fired.

## Context

- Investor: {investor_name} (id: {args.investor_id})
- Original pass reason: {pass_reason}
- Re-approach trigger: {reapproach_trigger}

## Draft (fill in <PLACEHOLDERS> when the milestone fires)

Subject: <SUBJECT — specific reference to the milestone, ≤80 chars>

Hi <FIRST NAME>,

Picking this back up — when we last spoke, the concern was: "{pass_reason}".

The milestone we agreed to track has hit: <FILL IN: dated, specific, verifiable
artifact tied to the reapproach_trigger above>. Specifically: <ONE SENTENCE>.

Want to take another 15 minutes? <PROPOSE TWO TIME WINDOWS or LINK>

— Herzel

## Rules

- ≤100 words total (excluding subject and signature).
- Do NOT claim the pass reason has been "fully solved" unless the milestone
  artifact actually proves it.
- Do not over-explain why you're reaching out — the milestone IS the reason.
- Voice-match against ~/fundraising/voice/voice-fingerprint.yaml. If
  voice_score < 0.7, set needs_human_review = high in outreach.csv.
- Run validate_outreach.py after exporting to outreach.csv.
"""

    try:
        target_path.write_text(template, encoding="utf-8")
    except OSError as exc:
        return emit_error(
            f"Failed to write {target_path}: {exc}",
            field=str(target_path),
            fix="Verify file permissions on ~/fundraising/outreach/.",
        )

    print(
        json.dumps(
            {
                "ok": True,
                "investor_id": args.investor_id,
                "investor_name": investor_name,
                "pass_reason": pass_reason,
                "reapproach_trigger": reapproach_trigger,
                "draft_path": str(target_path),
            }
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
