#!/usr/bin/env python3
"""
warm_list.py — preseed-pipeline

Reads pipeline.csv. Finds investors where:
  - status = 'nurture'
  - days_since_last_warm_touch >= 21

Categorizes by cadence band:
  - 21d  (21–44 days)
  - 45d  (45–89 days)
  - 90d  (90+ days)
  - upcoming (15–20 days — soft heads-up only)

Writes ~/fundraising/pipeline/warm-list.md with a sorted action list.
Prints JSON summary on stdout. Exit 1 on any error.

Stdlib only.
"""
from __future__ import annotations

import csv
import json
import sys
from datetime import date, datetime
from pathlib import Path

FUNDRAISING = Path.home() / "fundraising"
PIPELINE_CSV = FUNDRAISING / "pipeline" / "pipeline.csv"
WARM_LIST_MD = FUNDRAISING / "pipeline" / "warm-list.md"


# Exit codes: 1 validation, 2 missing input, 3 dependency, 4 unsafe.
def emit_error(message: str, field: str, fix: str, code: int = 1) -> int:
    print(json.dumps({"error": message, "field": field, "fix": fix}))
    return code


def parse_iso(value: str) -> date | None:
    value = (value or "").strip()
    if not value:
        return None
    try:
        return datetime.fromisoformat(value).date()
    except ValueError:
        return None


def main() -> int:
    if not PIPELINE_CSV.exists():
        return emit_error(
            "pipeline.csv not found",
            field=str(PIPELINE_CSV),
            fix="Run /preseed-campaign setup to initialize pipeline files.",
        )

    today = date.today()

    overdue_90: list[dict[str, str | int]] = []
    overdue_45: list[dict[str, str | int]] = []
    overdue_21: list[dict[str, str | int]] = []
    upcoming: list[dict[str, str | int]] = []
    holding: list[dict[str, str | int]] = []

    nurture_count = 0

    try:
        with PIPELINE_CSV.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            for row in reader:
                status = (row.get("status") or "").strip()
                if status != "nurture":
                    continue
                nurture_count += 1
                last_warm = parse_iso(row.get("last_warm_touch") or "")
                if not last_warm:
                    # Treat as 90+ overdue if missing — never touched warmly.
                    days_since = 999
                else:
                    days_since = (today - last_warm).days

                entry = {
                    "investor_id": (row.get("investor_id") or "").strip(),
                    "investor_name": (row.get("investor_name") or "").strip(),
                    "last_warm_touch": (row.get("last_warm_touch") or "").strip(),
                    "days_since": days_since,
                    "score_10": (row.get("score_10") or "").strip(),
                    "lead_candidate": (row.get("lead_candidate") or "").strip(),
                }

                if days_since >= 90:
                    entry["band"] = "90d"
                    overdue_90.append(entry)
                elif days_since >= 45:
                    entry["band"] = "45d"
                    overdue_45.append(entry)
                elif days_since >= 21:
                    entry["band"] = "21d"
                    overdue_21.append(entry)
                elif days_since >= 15:
                    entry["band"] = "upcoming"
                    upcoming.append(entry)
                else:
                    entry["band"] = "holding"
                    holding.append(entry)
    except (OSError, csv.Error) as exc:
        return emit_error(
            f"Failed to read pipeline.csv: {exc}",
            field=str(PIPELINE_CSV),
            fix="Verify the file is valid CSV with a header row.",
        )

    for bucket in (overdue_90, overdue_45, overdue_21, upcoming, holding):
        bucket.sort(key=lambda e: -e["days_since"])  # type: ignore[arg-type]

    # --- Render markdown.
    lines: list[str] = []
    lines.append(f"# Warm List — {today.isoformat()}")
    lines.append("")
    lines.append("Generated by warm_list.py. Do not hand-edit.")
    lines.append("")
    lines.append(f"Total nurture investors: {nurture_count}")
    overdue_total = len(overdue_90) + len(overdue_45) + len(overdue_21)
    lines.append(f"Overdue (action this week): {overdue_total}")
    lines.append("")

    def render_band(title: str, items: list[dict], frame: str) -> None:
        lines.append(f"### {title}")
        if not items:
            lines.append("- (none)")
            lines.append("")
            return
        lines.append("")
        for entry in items:
            display = entry["investor_name"] or entry["investor_id"]
            lead = " (lead candidate)" if (entry["lead_candidate"] or "").lower() == "yes" else ""
            lines.append(
                f"- {display}{lead} — last warm touch: "
                f"{entry['last_warm_touch'] or 'never'}, "
                f"days since: {entry['days_since']} — frame: {frame}"
            )
        lines.append("")

    lines.append("## Overdue (action this week)")
    lines.append("")
    render_band(
        "90-day (final nudge — moves to do_not_contact if no reply)",
        overdue_90,
        "round status + soft-circle descriptor",
    )
    render_band(
        "45-day (second nudge — product/thesis update)",
        overdue_45,
        "what's changed since last touch",
    )
    render_band(
        "21-day (first nudge — milestone)",
        overdue_21,
        "most recent shipped milestone",
    )

    lines.append("## Upcoming (this week)")
    lines.append("")
    if not upcoming:
        lines.append("- (none)")
    else:
        for entry in upcoming:
            display = entry["investor_name"] or entry["investor_id"]
            due_in = 21 - int(entry["days_since"])  # type: ignore[arg-type]
            lines.append(
                f"- {display} — last warm touch: {entry['last_warm_touch']}, "
                f"due in {due_in} days at the 21-day mark"
            )
    lines.append("")

    lines.append("## Holding")
    lines.append("")
    if not holding:
        lines.append("- (none)")
    else:
        for entry in holding[:20]:
            display = entry["investor_name"] or entry["investor_id"]
            next_in = 21 - int(entry["days_since"])  # type: ignore[arg-type]
            lines.append(
                f"- {display} — last warm touch: {entry['last_warm_touch']}, "
                f"next touch in {max(next_in, 0)} days"
            )
    lines.append("")

    lines.append("## Notes")
    lines.append("")
    lines.append(
        "- Action overdue 90-day touches first; they're the highest-conversion "
        "group at close."
    )
    lines.append(
        "- Use /preseed-outreach warm-update [investor_id] to draft each touch. "
        "Each warm update is ≤150 words and milestone-anchored."
    )
    lines.append(
        "- Investors at 90+ days with no positive signal move to "
        "do_not_contact for this round (re-evaluate next round)."
    )
    lines.append("")

    WARM_LIST_MD.parent.mkdir(parents=True, exist_ok=True)
    WARM_LIST_MD.write_text("\n".join(lines), encoding="utf-8")

    summary = {
        "ok": True,
        "warm_list_path": str(WARM_LIST_MD),
        "nurture_total": nurture_count,
        "overdue_90": [e["investor_id"] for e in overdue_90],
        "overdue_45": [e["investor_id"] for e in overdue_45],
        "overdue_21": [e["investor_id"] for e in overdue_21],
        "upcoming": [e["investor_id"] for e in upcoming],
    }
    print(json.dumps(summary))
    return 0


if __name__ == "__main__":
    sys.exit(main())
